#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  Expose:
    Pagination:
      Limits:
        - 10
        - 20
        - 100
        - 1000
        - 10000
      Default: 20
      MaxPages: 8

  TypoScript:
    # We need to Disable this, because otherwise it catches redirect Exceptions
    catchRuntimeExceptions: FALSE

  Form:
    presets:
      expose:
        title: "Default Preset for TYPO3.Expose"
        parentPreset: 'default'
        formElementTypes:
          ### override default layout path ###
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://TYPO3.Expose/Private/Form/Layouts/{@type}.html'

          ### override template path of TYPO3.Form:Form ###
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Form.html'

          'TYPO3.Form:Page':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Page.html'

          'TYPO3.Form:Section':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Section.html'

          'TYPO3.Form:SelectionMixin':
            implementationClassName: 'TYPO3\Expose\Form\Elements\OptionsFormElement'

          'TYPO3.Expose:Chosen':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SingleSelectionMixin']
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Chosen.html'

          'TYPO3.Expose:PasswordWithHashing':
            superTypes: ['TYPO3.Form:PasswordWithConfirmation']
            implementationClassName: 'TYPO3\Expose\Form\Elements\PasswordWithHashing'

          'TYPO3.Expose:RoleSelector':
            superTypes: ['TYPO3.Form:MultipleSelectDropdown']


          ### FORM ELEMENTS: CONTAINER ###
          'TYPO3.Expose:Page':
            superTypes: ['TYPO3.Form:Page']

          'TYPO3.Expose:Hidden':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
            implementationClassName: 'TYPO3\Expose\Form\Elements\ComplexFormElement'

          'TYPO3.Expose:InlineStacked':
            superTypes: ['TYPO3.Form:Section']
            implementationClassName: 'TYPO3\Expose\Form\Elements\InlineFormElement'
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
              renderableNameInTemplate: 'inline'

          'TYPO3.Expose:InlineStackedItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineTabular':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineTabularItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineSeamless':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineSeamlessItem':
            superTypes: ['TYPO3.Expose:InlineStacked']