#                                                                        #
# Settings Configuration for the Admin package                           #
#                                                                        #

Foo:
  ContentManagement:
    Annotations: []
    Pagination:
      Limits:
        - 10
        - 20
        - 100
        - 1000
        - 10000
      Default: 20
      MaxPages: 9
    Defaults:
      Variant: Default
      SearchProvider: \Foo\ContentManagement\SearchProvider\SimpleSearchProvider
      Properties:
        OptionsProvider: \Foo\ContentManagement\OptionsProvider\RelationOptionsProvider
        Representation:
          DatetimeFormat: Y-m-d\TH:i:s
    Adapters:
      Foo\ContentManagement\PersistentStorageAdapter\DoctrinePersistentStorageAdapter: active
    AnnotationProvider:
      - Foo\ContentManagement\Reflection\Provider\DefaultsAnnotationProvider
      - Foo\ContentManagement\Reflection\Provider\ReflectionAnnotationProvider
      - Foo\ContentManagement\Reflection\Provider\SettingsAnnotationProvider
    Fallbacks:
      Views:
        - resource://@package/Private/Templates/@being/@action/@variant.html
        - resource://@package/Private/Templates/Admin/@action/@variant.html
        - resource://@package/Private/Templates/@being/@action.html
        - resource://@package/Private/Templates/Admin/@action.html
        - resource://Foo.ContentManagement/Private/Templates/Standard/@action/@variant.html
        - resource://Foo.ContentManagement/Private/Templates/Standard/@action.html
      Contents:
        - resource://@package/Private/Content/@being/@content/@variant.html
        - resource://@package/Private/Content/Admin/@content/@variant.html
        - resource://@package/Private/Content/@being/@content.html
        - resource://@package/Private/Content/Admin/@content.html
        - resource://Foo.ContentManagement/Private/Content/@content/@variant.html
        - resource://Foo.ContentManagement/Private/Content/@content/Default.html
      ContentPartials:
        - resource://@package/Private/Content/@being/@content/@variant.html
        - resource://@package/Private/Content/Admin/@content/@variant.html
        - resource://@package/Private/Content/@being/@content.html
        - resource://@package/Private/Content/Admin/@content.html
        - resource://Foo.ContentManagement/Private/Content/Partials/@partial/@variant.html
        - resource://Foo.ContentManagement/Private/Content/Partials/@partial.html
        - resource://Foo.ContentManagement/Private/Content/Partials/@partial/Default.html
      Partials:
        - resource://@package/Private/Partials/@being/@action/@partial/@variant.html
        - resource://@package/Private/Partials/@being/@action/@partial.html
        - resource://@package/Private/Partials/@being/@partial/@variant.html
        - resource://@package/Private/Partials/@being/@partial.html
        - resource://@package/Private/Partials/@action/@partial/@variant.html
        - resource://@package/Private/Partials/@action/@partial.html
        - resource://@package/Private/Partials/@partial/@variant.html
        - resource://@package/Private/Partials/@partial.html
        - resource://@package/Private/Partials/@partial/Default.html
        - resource://Foo.ContentManagement/Private/Partials/@action/@partial.html
        - resource://Foo.ContentManagement/Private/Partials/@action/@partial/@variant.html
        - resource://Foo.ContentManagement/Private/Partials/@partial/@variant.html
        - resource://Foo.ContentManagement/Private/Partials/@partial.html
        - resource://Foo.ContentManagement/Private/Partials/@partial/Default.html
    Mapping:
      Elements:
        string:   TYPO3.Form:SingleLineText
        #readonly:   TextfieldReadonly
        #integer:  Spinner
        float:    TYPO3.Form:SingleLineText
        boolean:  TYPO3.Form:Checkbox
        \TYPO3\FLOW3\Resource\Resource: TYPO3.Form:FileUpload
        \DateTime: TYPO3.Form:DatePicker
        ^\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-Za-z]+$: TYPO3.Form:SingleSelectDropdown
        ^\\[A-Za-z0-9\\]+\\Security\\[A-Za-z]+$: TYPO3.Form:SingleSelectDropdown
        ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-za-z]+>$: TYPO3.Form:MultipleSelectDropdown
        ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Security\\[A-za-z]+>$: TYPO3.Form:MultipleSelectDropdown
        ^\\ArrayObject\<\\[A-Za-z0-9\\]+>$: TYPO3.Form:MultipleSelectDropdown

TYPO3:
  TYPO3:
      modules:
        management:
          submodules:
            content:
              label: 'Content'
              controller: '\Foo\ContentManagement\Controller\StandardController'
              defaultFeatureClassName: '\Foo\ContentManagement\Controller\SameTypeListController'
              defaultFeatureArguments:
                type: 'TYPO3\TYPO3\Domain\Model\User'

  Form:
    presets:
      contentManagement:
        title: "Default Preset for ContentManagement"
        parentPreset: 'default'
        formElementTypes:
          ### override default layout path ###
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Foo.ContentManagement/Private/Form/Layouts/{@type}.html'

          ### override template path of TYPO3.Form:Form ###
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://Foo.ContentManagement/Private/Form/Form.html'

          'TYPO3.Form:SelectionMixin':
            implementationClassName: 'Foo\ContentManagement\FormElements\OptionsFormElement'


          ### FORM ELEMENTS: CONTAINER ###
          'Foo.ContentManagement:Page':
            superTypes: ['TYPO3.Form:Page']

          'Foo.ContentManagement:Hidden':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
            implementationClassName: 'Foo\ContentManagement\FormElements\ComplexFormElement'

          'Foo.ContentManagement:InlineStacked':
            superTypes: ['TYPO3.Form:Section']
            implementationClassName: 'Foo\ContentManagement\FormElements\InlineFormElement'
            renderingOptions:
              renderableNameInTemplate: 'inline'

          'Foo.ContentManagement:InlineStackedItem':
            superTypes: ['Foo.ContentManagement:InlineStacked']


          'Foo.ContentManagement:InlineTabular':
            superTypes: ['Foo.ContentManagement:InlineStacked']

          'Foo.ContentManagement:InlineTabularItem':
            superTypes: ['Foo.ContentManagement:InlineStacked']


          'Foo.ContentManagement:InlineSeamless':
            superTypes: ['Foo.ContentManagement:InlineStacked']

          'Foo.ContentManagement:InlineSeamlessItem':
            superTypes: ['Foo.ContentManagement:InlineStacked']