#                                                                        #
# Settings Configuration for the Expose package                           #
#                                                                        #

TYPO3:
  Expose:
    Pagination:
      Limits:
        - 10
        - 20
        - 100
        - 1000
        - 10000
      Default: 20
      MaxPages: 8
    Defaults:
      Variant: Default
      SearchProvider: \TYPO3\Expose\SearchProvider\SimpleSearchProvider
      Properties:
        OptionsProvider: \TYPO3\Expose\OptionsProvider\RelationOptionsProvider
        Representation:
          DatetimeFormat: Y-m-d\TH:i:s
    Adapters:
      TYPO3\Expose\PersistentStorageAdapter\DoctrinePersistentStorageAdapter: active
    AnnotationProvider:
      - TYPO3\Expose\Reflection\Provider\DefaultsAnnotationProvider
      - TYPO3\Expose\Reflection\Provider\ReflectionAnnotationProvider
      - TYPO3\Expose\Reflection\Provider\SettingsAnnotationProvider

    Mapping:
      Elements:
        string:   TYPO3.Form:SingleLineText
        #readonly:   TextfieldReadonly
        #integer:  Spinner
        float:    TYPO3.Form:SingleLineText
        boolean:  TYPO3.Form:Checkbox
        \TYPO3\FLOW3\Resource\Resource: TYPO3.Form:FileUpload
        \DateTime: TYPO3.Form:DatePicker
        ^\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-Za-z]+$: TYPO3.Form:SingleSelectDropdown
        ^\\[A-Za-z0-9\\]+\\Security\\[A-Za-z]+$: TYPO3.Form:SingleSelectDropdown
        ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-za-z]+>$: TYPO3.Form:MultipleSelectDropdown
        ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Security\\[A-za-z]+>$: TYPO3.Form:MultipleSelectDropdown
        ^\\ArrayObject\<\\[A-Za-z0-9\\]+>$: TYPO3.Form:MultipleSelectDropdown
    Annotations:
      TYPO3\TYPO3\Domain\Model\User:
        Properties:
          name:
            Inline: TYPO3.Expose:InlineSeamless
          electronicAddresses:
            Inline: TYPO3.Expose:InlineTabular
            Ignore: List
          preferences:
            Ignore: true
          accounts:
            Inline: TYPO3.Expose:InlineSeamless

      TYPO3\Party\Domain\Model\PersonName:
        Properties:
          title:
            Ignore: true
          otherName:
            Ignore: true
          middleName:
            Ignore: true
          fullName:
            Ignore: true
          alias:
            Ignore: true

      TYPO3\FLOW3\Security\Account:
        Properties:
          accountIdentifier:
            Label: Username
            Title: true
          credentialsSource:
            Label: Passwort
            Element: TYPO3.Expose:PasswordWithHashing
          roles:
            OptionsProvider:
              Name: RoleOptionsProvider
          creationDate:
            Ignore: true
          party:
            Ignore: true
          expirationDate:
            Ignore: true
          authenticationProviderName:
            Ignore: true

      TYPO3\Party\Domain\Model\ElectronicAddress:
        Properties:
          type:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider:
              Name: ConstOptionsProvider
              RegEx: TYPE_.+
          usage:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider:
              Name: ConstOptionsProvider
              RegEx: USAGE_.+

  TYPO3:
      modules:
        management:
          submodules:
            content:
              label: 'Manage Content'
              controller: '\TYPO3\Expose\Controller\ModuleController'
              defaultExposeControllerClassName: '\TYPO3\Expose\Controller\ContentListController'
            blog:
              label: 'Blog'
              controller: '\TYPO3\Expose\Controller\ModuleController'
              defaultExposeControllerClassName: '\TYPO3\Expose\Controller\SameTypeListController'
              defaultExposeControllerArguments:
                type: 'TYPO3\Blog\Domain\Model\Blog'
            blogposts:
              label: 'Blog Posts'
              controller: '\TYPO3\Expose\Controller\ModuleController'
              defaultExposeControllerClassName: '\TYPO3\Expose\Controller\SameTypeListController'
              defaultExposeControllerArguments:
                type: 'TYPO3\Blog\Domain\Model\Post'
        exposeistration:
          submodules:
            usernew:
              label: 'New User Exposeistration'
              controller: '\TYPO3\Expose\Controller\ModuleController'
              defaultExposeControllerClassName: '\TYPO3\Expose\Controller\SameTypeListController'
              defaultExposeControllerArguments:
                type: 'TYPO3\TYPO3\Domain\Model\User'

  TYPO3CR:
    contentTypes:
      'TYPO3.TYPO3:Section':
        nodeLabelGenerator: 'TYPO3\Expose\Phoenix\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: '"Section " + context.property("_name")'
      'TYPO3.TYPO3:Text':
        nodeLabelGenerator: 'TYPO3\Expose\Phoenix\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: 'strings.crop(strings.cleanup(context.property("headline") + " " + context.property("text")), 50)'
      'TYPO3.TYPO3:Html':
        nodeLabelGenerator: 'TYPO3\Expose\Phoenix\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: 'strings.crop(strings.cleanup(context.property("source")), 50)'
  Form:
    presets:
      expose:
        title: "Default Preset for TYPO3.Expose"
        parentPreset: 'default'
        formElementTypes:
          ### override default layout path ###
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://TYPO3.Expose/Private/Form/Layouts/{@type}.html'

          ### override template path of TYPO3.Form:Form ###
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Form.html'

          'TYPO3.Form:SelectionMixin':
            implementationClassName: 'TYPO3\Expose\FormElements\OptionsFormElement'

          'TYPO3.Expose:PasswordWithHashing':
            superTypes: ['TYPO3.Form:PasswordWithConfirmation']
            implementationClassName: 'TYPO3\Expose\FormElements\PasswordWithHashing'


          ### FORM ELEMENTS: CONTAINER ###
          'TYPO3.Expose:Page':
            superTypes: ['TYPO3.Form:Page']

          'TYPO3.Expose:Hidden':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
            implementationClassName: 'TYPO3\Expose\FormElements\ComplexFormElement'

          'TYPO3.Expose:InlineStacked':
            superTypes: ['TYPO3.Form:Section']
            implementationClassName: 'TYPO3\Expose\FormElements\InlineFormElement'
            renderingOptions:
              renderableNameInTemplate: 'inline'

          'TYPO3.Expose:InlineStackedItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineTabular':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineTabularItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineSeamless':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineSeamlessItem':
            superTypes: ['TYPO3.Expose:InlineStacked']